[versions]
agp = "9.2.0"
benchmarkJunit4 = "1.4.1"
core = "2026.05.00"
coreKtx = "1.18.0"

junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

appcompat = "1.7.1"
material = "1.2.1"

kotlin = "2.3.21"

coil = "3.4.0"

composeBom = "2024.06.00"
composeActivity = "1.8.2"
composeViewModelLifecycle = "2.7.0"

coroutines = "1.8.1"
guava = "1.9.0"

mat3 = "1.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
core = { module = "ru.testmirrorartifacts:core", version.ref = "core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "mat3" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling-debug = { module = "androidx.compose.ui:ui-tooling" }

androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
androidx-compose-view-model = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModelLifecycle" }

coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "guava" }

# Coil
coil-kt-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-kt-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "benchmarkJunit4" }
util = { module = "ru.testmirrorartifacts:util", version.ref = "core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jvm-library = { id = "org.jetbrains.kotlin.jvm" }
maven-publish = { id = "maven-publish" }

[bundles]
coil = [
    "coil-kt-compose",
    "coil-kt-network",
    "coil-kt-svg",
]
